modules/BookManagement.Modules.Web/Pages/Authors/Create.cshtml.cs
using BookManagement.Modules.Web.Models;
using BookManagement.Modules.Web.Models.AuthorModels;
using BookManagement.Modules.Web.PageFilters;
using BookManagement.Modules.Web.Services.AuthorServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BookManagement.Modules.Web.Pages.Authors;

[ServiceFilter(typeof(TransactionPageFilter))]
public class CreateModel : BasePageModel
{
    private readonly IAuthorPageService _authorPageService;

    public CreateModel(IAuthorPageService authorPageService)
    {
        _authorPageService = authorPageService;
    }

    [BindProperty] public AuthorModel AuthorModel { get; set; }

    public IActionResult OnGet()
    {
        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
            return Page();

        CommandResult = await _authorPageService.CreateAsync(AuthorModel);

        if (CommandResult.Success)
            return RedirectToPage("./Index");

        return Page();
    }
}

modules/BookManagement.Modules.Web/Pages/Authors/Delete.cshtml.cs
using BookManagement.Core.Domain.Queries.AuthorQueries.QueryResults;
using BookManagement.Modules.Web.Models;
using BookManagement.Modules.Web.PageFilters;
using BookManagement.Modules.Web.Services.AuthorServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BookManagement.Modules.Web.Pages.Authors;

[ServiceFilter(typeof(TransactionPageFilter))]
public class DeleteModel : BasePageModel
{
    private readonly IAuthorPageService _authorPageService;

    public DeleteModel(IAuthorPageService authorPageService)
    {
        _authorPageService = authorPageService;
    }

    [BindProperty] public AuthorQueryResult Author { get; set; }

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id is null)
            return NotFound();

        var author = await _authorPageService.GetByIdAsync(id.Value);
        if (author is null)
            return NotFound();

        Author = author;

        return Page();
    }

    public async Task<IActionResult> OnPostAsync(Guid? id)
    {
        if (id is null)
            return NotFound();

        var author = await _authorPageService.GetByIdAsync(id.Value);
        if (author is null)
            return NotFound();

        CommandResult = await _authorPageService.DeleteAsync(id.Value);

        return RedirectToPage("./Index");
    }
}

modules/BookManagement.Modules.Web/Pages/Authors/Details.cshtml.cs
using BookManagement.Core.Domain.Queries.AuthorQueries.QueryResults;
using BookManagement.Modules.Web.Services.AuthorServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;

namespace BookManagement.Modules.Web.Pages.Authors;

public class DetailsModel : PageModel
{
    private readonly IAuthorPageService _authorPageService;

    public DetailsModel(IAuthorPageService authorPageService)
    {
        _authorPageService = authorPageService;
    }

    public AuthorQueryResult Author { get; set; }

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id is null)
            return NotFound();

        var author = await _authorPageService.GetByIdAsync(id.Value);
        if (author is null)
            return NotFound();

        Author = author;

        return Page();
    }
}

modules/BookManagement.Modules.Web/Pages/Authors/Edit.cshtml.cs
using BookManagement.Modules.Web.Models;
using BookManagement.Modules.Web.Models.AuthorModels;
using BookManagement.Modules.Web.PageFilters;
using BookManagement.Modules.Web.Services.AuthorServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BookManagement.Modules.Web.Pages.Authors;

[ServiceFilter(typeof(TransactionPageFilter))]
public class EditModel : BasePageModel
{
    private readonly IAuthorPageService _authorPageService;

    public EditModel(IAuthorPageService authorPageService)
    {
        _authorPageService = authorPageService;
    }

    [BindProperty] public AuthorModel AuthorModel { get; set; } = default!;

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id is null)
            return NotFound();

        var author = await _authorPageService.GetByIdAsync(id.Value);
        if (author is null)
            return NotFound();

        AuthorModel = AuthorModel.FromQueryResult(author);

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
            return Page();

        if (!AuthorModel.Id.HasValue || !await AuthorExists(AuthorModel.Name))
            return NotFound();

        CommandResult = await _authorPageService.UpdateAsync(AuthorModel);

        if (CommandResult.Success)
            return RedirectToPage("./Index");

        return Page();
    }

    private async Task<bool> AuthorExists(string name)
    {
        return await _authorPageService.AuthorExistsAsync(name);
    }
}

modules/BookManagement.Modules.Web/Pages/Books/Create.cshtml.cs
using BookManagement.Modules.Web.Models;
using BookManagement.Modules.Web.Models.BookModels;
using BookManagement.Modules.Web.PageFilters;
using BookManagement.Modules.Web.Services.BookServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BookManagement.Modules.Web.Pages.Books;

[ServiceFilter(typeof(TransactionPageFilter))]
public class CreateModel : BasePageModel
{
    private readonly IBookPageService _bookPageService;

    public CreateModel(IBookPageService bookPageService)
    {
        _bookPageService = bookPageService;
    }

    [BindProperty] public BookModel BookModel { get; set; }

    public IActionResult OnGet()
    {
        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
            return Page();

        CommandResult = await _bookPageService.CreateAsync(BookModel);

        if (CommandResult.Success)
            return RedirectToPage("./Index");

        return Page();
    }
}

modules/BookManagement.Modules.Web/Pages/Books/Delete.cshtml.cs
using BookManagement.Core.Domain.Queries.BookQueries.QueryResults;
using BookManagement.Modules.Web.Models;
using BookManagement.Modules.Web.PageFilters;
using BookManagement.Modules.Web.Services.BookServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BookManagement.Modules.Web.Pages.Books;

[ServiceFilter(typeof(TransactionPageFilter))]
public class DeleteModel : BasePageModel
{
    private readonly IBookPageService _bookPageService;

    public DeleteModel(IBookPageService bookPageService)
    {
        _bookPageService = bookPageService;
    }

    [BindProperty] public BookQueryResult Book { get; set; }

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id is null)
            return NotFound();

        var book = await _bookPageService.GetByIdAsync(id.Value);
        if (book is null)
            return NotFound();

        Book = book;

        return Page();
    }

    public async Task<IActionResult> OnPostAsync(Guid? id)
    {
        if (id is null)
            return NotFound();

        var book = await _bookPageService.GetByIdAsync(id.Value);
        if (book is null)
            return NotFound();

        CommandResult = await _bookPageService.DeleteAsync(id.Value);

        return RedirectToPage("./Index");
    }
}

modules/BookManagement.Modules.Web/Pages/Books/Details.cshtml.cs
using BookManagement.Core.Domain.Queries.BookQueries.QueryResults;
using BookManagement.Modules.Web.Services.BookServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;

namespace BookManagement.Modules.Web.Pages.Books;

public class DetailsModel : PageModel
{
    private readonly IBookPageService _bookPageService;

    public DetailsModel(IBookPageService bookPageService)
    {
        _bookPageService = bookPageService;
    }

    public BookQueryResult Book { get; set; }

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id is null)
            return NotFound();

        var book = await _bookPageService.GetByIdAsync(id.Value);
        if (book is null)
            return NotFound();

        Book = book;

        return Page();
    }
}

modules/BookManagement.Modules.Web/Pages/Books/Edit.cshtml.cs
using BookManagement.Modules.Web.Models;
using BookManagement.Modules.Web.Models.BookModels;
using BookManagement.Modules.Web.PageFilters;
using BookManagement.Modules.Web.Services.BookServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BookManagement.Modules.Web.Pages.Books;

[ServiceFilter(typeof(TransactionPageFilter))]
public class EditModel : BasePageModel
{
    private readonly IBookPageService _bookPageService;

    public EditModel(IBookPageService bookPageService)
    {
        _bookPageService = bookPageService;
    }

    [BindProperty] public BookModel BookModel { get; set; } = default!;

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id is null)
            return NotFound();

        var book = await _bookPageService.GetByIdAsync(id.Value);
        if (book is null)
            return NotFound();

        BookModel = BookModel.FromQueryResult(book);

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
            return Page();

        if (!BookModel.Id.HasValue || !await BookExists(BookModel.Isbn10, BookModel.Isbn13))
            return NotFound();

        CommandResult = await _bookPageService.UpdateAsync(BookModel);

        if (CommandResult.Success)
            return RedirectToPage("./Index");

        return Page();
    }

    private async Task<bool> BookExists(string isbn10, string isbn13)
    {
        return await _bookPageService.BookExistsAsync(isbn10, isbn13);
    }
}

modules/BookManagement.Modules.Web/Pages/Books/Index.cshtml.cs
using BookManagement.Core.Domain.Queries.BookQueries.Inputs;
using BookManagement.Core.Domain.Queries.BookQueries.QueryResults;
using BookManagement.Core.Shared.Queries.Interfaces.QueryResults;
using BookManagement.Modules.Web.Models;
using BookManagement.Modules.Web.Services.BookServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Threading.Tasks;

namespace BookManagement.Modules.Web.Pages.Books;

public class IndexModel : PaginationPageModel
{
    private readonly IBookPageService _bookPageService;
    public IPaginateQueryResult<BookQueryResult> Books { get; set; } = default!;

    public IndexModel(IBookPageService bookPageService)
    {
        _bookPageService = bookPageService;
    }

    [BindProperty(SupportsGet = true)]
    public string Title { get; set; }

    public async Task OnGetAsync()
    {
        var filter = new FilterBookQueries
        {
            CurrentPage = CurrentPage,
            Title = Title,
            OrderBy = Sort,
            PageSize = 5
        };

        Books = await _bookPageService.GetPaginatedAsync(filter);
    }

    public override void OnPageHandlerExecuted(PageHandlerExecutedContext context)
    {
        AddPaginationData("title", Title);
        AddPaginationData("page", Books?.CurrentPage.ToString());
        base.OnPageHandlerExecuted(context);
    }
}

modules/BookManagement.Modules.Web/Pages/Categories/Create.cshtml.cs
using BookManagement.Modules.Web.Models;
using BookManagement.Modules.Web.Models.CategoryModels;
using BookManagement.Modules.Web.PageFilters;
using BookManagement.Modules.Web.Services.CategoryServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace BookManagement.Modules.Web.Pages.Categories;

[ServiceFilter(typeof(TransactionPageFilter))]
public class CreateModel : BasePageModel
{
    private readonly ICategoryPageService _categoryPageService;

    public CreateModel(ICategoryPageService categoryPageService)
    {
        _categoryPageService = categoryPageService;
    }

    [BindProperty] public CategoryModel CategoryModel { get; set; }

    public SelectList CategoriesSelectList { get; set; }

    public async Task<IActionResult> OnGet()
    {
        await LoadParentCategories();
        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        await LoadParentCategories();

        if (!ModelState.IsValid)
            return Page();

        CommandResult = await _categoryPageService.CreateAsync(CategoryModel);

        if (CommandResult.Success)
            return RedirectToPage("./Index");

        return Page();
    }

    public async Task LoadParentCategories()
    {
        var categories = await _categoryPageService.GetAllAsync();
        CategoriesSelectList = CreateSelectList(categories.Select(x => new SelectListModel(x.Id, x.Name)), "Id", "Name");
    }
}

modules/BookManagement.Modules.Web/Pages/Categories/Delete.cshtml.cs
using BookManagement.Core.Domain.Queries.CategoryQueries.QueryResults;
using BookManagement.Modules.Web.Models;
using BookManagement.Modules.Web.PageFilters;
using BookManagement.Modules.Web.Services.CategoryServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BookManagement.Modules.Web.Pages.Categories;

[ServiceFilter(typeof(TransactionPageFilter))]
public class DeleteModel : BasePageModel
{
    private readonly ICategoryPageService _categoryPageService;

    public DeleteModel(ICategoryPageService categoryPageService)
    {
        _categoryPageService = categoryPageService;
    }

    [BindProperty] public CategoryQueryResult Category { get; set; }

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id is null)
            return NotFound();

        var category = await _categoryPageService.GetByIdAsync(id.Value);

        if (category is null)
            return NotFound();

        Category = category;

        return Page();
    }

    public async Task<IActionResult> OnPostAsync(Guid? id)
    {
        if (id is null)
            return NotFound();

        var category = await _categoryPageService.GetByIdAsync(id.Value);

        if (category is null)
            return NotFound();

        CommandResult = await _categoryPageService.DeleteAsync(id.Value);

        return RedirectToPage("./Index");
    }
}

modules/BookManagement.Modules.Web/Pages/Categories/Details.cshtml.cs
using BookManagement.Core.Domain.Queries.CategoryQueries.QueryResults;
using BookManagement.Modules.Web.Services.CategoryServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;

namespace BookManagement.Modules.Web.Pages.Categories;

public class DetailsModel : PageModel
{
    private readonly ICategoryPageService _categoryPageService;

    public DetailsModel(ICategoryPageService categoryPageService)
    {
        _categoryPageService = categoryPageService;
    }

    public CategoryQueryResult Category { get; set; }

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id == null)
            return NotFound();

        var category = await _categoryPageService.GetByIdAsync(id.Value);
        if (category == null)
            return NotFound();

        Category = category;

        return Page();
    }
}

modules/BookManagement.Modules.Web/Pages/Publishers/Create.cshtml.cs
using BookManagement.Modules.Web.Models;
using BookManagement.Modules.Web.Models.PublisherModels;
using BookManagement.Modules.Web.PageFilters;
using BookManagement.Modules.Web.Services.PublisherServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BookManagement.Modules.Web.Pages.Publishers;

[ServiceFilter(typeof(TransactionPageFilter))]
public class CreateModel : BasePageModel
{
    private readonly IPublisherPageService _publisherPageService;

    public CreateModel(IPublisherPageService publisherPageService)
    {
        _publisherPageService = publisherPageService;
    }

    [BindProperty] public PublisherModel PublisherModel { get; set; }

    public IActionResult OnGet()
    {
        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
            return Page();

        CommandResult = await _publisherPageService.CreateAsync(PublisherModel);

        if (CommandResult.Success)
            return RedirectToPage("./Index");

        return Page();
    }
}

modules/BookManagement.Modules.Web/ViewComponents/PaginationViewComponent.cs
using BookManagement.Core.Shared.Queries.Interfaces.QueryResults;
using BookManagement.Modules.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookManagement.Modules.Web.ViewComponents;

public class PaginationViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(IPaginateQueryResult<object> paginatedValues)
    {
        return View("Default", new PaginationModel
        {
            List = paginatedValues,
            RouteData = null
        });
    }
}

modules/BookManagement.Modules.Web/Pages/Books/Create.cshtml
@page
@model CreateModel

@{
    ViewData["Title"] = "Create";
}

<h4>Create Book</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BookModel.Title" class="control-label"></label>
                <input asp-for="BookModel.Title" class="form-control"/>
                <span asp-validation-for="BookModel.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookModel.Description" class="control-label"></label>
                <input asp-for="BookModel.Description" class="form-control"/>
                <span asp-validation-for="BookModel.Description" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

modules/BookManagement.Modules.Web/Pages/Books/Delete.cshtml
@page
@model DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Description)
        </dd>
    </dl>

    <form method="post">
        <input type="hidden" asp-for="Book.Id"/>
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

modules/BookManagement.Modules.Web/Pages/Books/Details.cshtml
@page
@model DetailsModel

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>Book Details</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Title)
        </dd>
        <dt class="col-sm-2">
            Description
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Book?.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

modules/BookManagement.Modules.Web/Pages/Books/Edit.cshtml
@page
@model EditModel

@{
    ViewData["Title"] = "Edit";
}

<h4>Edit Book</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BookModel.Title" class="control-label"></label>
                <input asp-for="BookModel.Title" class="form-control"/>
                <span asp-validation-for="BookModel.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookModel.Description" class="control-label"></label>
                <input asp-for="BookModel.Description" class="form-control"/>
                <span asp-validation-for="BookModel.Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="BookModel.Id"/>
            <div class="form-group mt-2">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

modules/BookManagement.Modules.Web/Pages/Books/Index.cshtml
@page
@model IndexModel

@{
    ViewData["Title"] = "Books List";
}

<div class="card">
    <div class="card-header">
        <h1>@ViewData["Title"]</h1>
        <div class="row">
            <div class="col-6">
                <form method="get" name="filterForm">
                    <input class="form-control" asp-for="Title" placeholder="Search by title" />
                </form>
            </div>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-hover">
            <thead class="table-dark">
                <tr>
                    <th scope="col">
                        Name
                    </th>
                    <th scope="col">
                        Category Name
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Books.Items)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CategoryName)
                        </td>
                        <td>
                            <a asp-page="./Edit" asp-route-id="@item.Id" class="btn btn-warning" data-bs-toggle="tooltip" data-bs-title="Edit">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                            <a asp-page="./Details" asp-route-id="@item.Id" class="btn btn-info" data-bs-toggle="tooltip" data-bs-title="Details">
                                <i class="fa-solid fa-search"></i>
                            </a>
                            <a asp-page="./Delete" asp-route-id="@item.Id" class="btn btn-danger" data-bs-toggle="tooltip" data-bs-title="Delete">
                                <i class="fa-solid fa-trash-can"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <div class="col-12">
            <a class="btn btn-outline-info float-end" asp-page="Create">Create New</a>
        </div>
        <div class="card-footer">
            <vc:pagination paginated-values="Model.Books.ToObjectQueryResult()" route-data="Model.LinkData"></vc:pagination>
        </div>
    </div>
</div>